### ISSUE TITLE
Add Quartz plugin to manage cron tasks

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/fieldguide#11]
The field guides server recently stopped working due to a disk filling up. This app appears to leave the generated PDFs on disk. The solution was to setup a cron task to delete files older than X days.

I'm suggesting we use the [Quartz plugin](http://plugins.grails.org/plugin/grails/quartz) to achieve the same outcome as cron, as it will ensure that if the application is moved to another server, the scheduled delete job won't be left behind. This has happened with other apps in the past on a few occasions.

**Comment by ansell** [comment]
Another potential solution to the storage problem is storing the fieldguides in Amazon S3 as we do with the other biocache downloads. Then we could have a biocache-wide solution for pushing things to Glacial or another slow storage when/if the online S3 downloads start to cost too much.

See #12 for the tracking ticket for that

**Comment by adam-collins** [comment]
S3 option available as a result of #32. 

Deployments currently relying on cron to free disk space will need to continue doing so. 

Closing because there is no immediate need for this.
