### ISSUE TITLE
Field Guide producing empty PDF

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/fieldguide#13]
**Describe the bug**
Notifed via the support queue https://support.ehelp.edu.au/a/tickets/32303
The Field Guide WS returns a PDF document but it doesn't contain any info.

**To Reproduce**

Run query

https://biocache.ala.org.au/occurrences/search?q=*%3A*&wkt=MULTIPOLYGON(((135.70449829101562%20-35.01185211042122%2C136.45706176757812%20-34.043404817602465%2C137.23159790039062%20-33.719618511595506%2C137.48428344726562%20-33.12359751760072%2C137.6600646972656%20-32.98547442175531%2C138.0335998535156%20-33.12359751760072%2C137.76992797851562%20-33.210963313018084%2C137.92922973632812%20-33.550398581136236%2C137.54470825195312%20-33.8246415415585%2C137.38540649414062%20-34.17530164737075%2C137.40188598632812%20-34.890286662377726%2C136.9734191894531%20-34.890286662377726%2C136.80313110351562%20-35.27238230299627%2C135.70449829101562%20-35.01185211042122)))

~~https://biocache.ala.org.au/occurrences/search?file=records-2019-05-09&reasonTypeId=12&dwcHeaders=true&fileType=csv&qa=none&sourceTypeId=0&q=*%3A*&wkt=MULTIPOLYGON(((135.70449829101562%20-35.01185211042122%2C136.45706176757812%20-34.043404817602465%2C137.23159790039062%20-33.719618511595506%2C137.48428344726562%20-33.12359751760072%2C137.6600646972656%20-32.98547442175531%2C138.0335998535156%20-33.12359751760072%2C137.76992797851562%20-33.210963313018084%2C137.92922973632812%20-33.550398581136236%2C137.54470825195312%20-33.8246415415585%2C137.38540649414062%20-34.17530164737075%2C137.40188598632812%20-34.890286662377726%2C136.9734191894531%20-34.890286662377726%2C136.80313110351562%20-35.27238230299627%2C135.70449829101562%20-35.01185211042122)))&&pageSize=0&&facet=true~~

Click 'Download'
Select Species Field Guide

**Expected behavior**
ALA User receives an email containing a link to a PDF download containing a list of species in the area 

**Actual behavior**
ALA user receives an email containing a link to a (for me, 1.1MB) PDF download containing headers and footers only. 

[09052019-fieldguide1557382357490.pdf](https://github.com/AtlasOfLivingAustralia/fieldguide/files/3160619/09052019-fieldguide1557382357490.pdf)

**Comment by nickdos** [comment]
I got a working PDF for this query:

https://biocache.ala.org.au/occurrences/search?q=lsid%3Ahttp%3A%2F%2Fid.biodiversity.org.au%2Fnode%2Fapni%2F6719673&fq=state%3A%22Australian%20Capital%20Territory%22&fq=month%3A%2203%22

PDF:

https://fieldguide.ala.org.au/download/offline/09052019-fieldguide1557385366026.pdf

**Comment by nickdos** [comment]
Got a related example of this via support ticket https://support.ehelp.edu.au/a/tickets/46490

Searhc produces empty guide: https://avh.ala.org.au/occurrences/search?q=collection_uid%3Aco54&qc=data_hub_uid%3Adh9

but if you filter on state or another facet, the field guide is complete.

This suggests there is an internal maximum limit (number of taxa to request from BIE is a guess) that is being exceeded and results in an exception or error.
