### ISSUE TITLE
Update ALA logo in PDF field guides

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/fieldguide#16]
![image](https://user-images.githubusercontent.com/532845/88142031-1e7d8980-cc38-11ea-9c70-ac796b92f114.png)

Still using the old logo. Should be using the new logo (see https://www.ala.org.au/ala-logo-and-identity/)

- [x] update to current logo
- [x] Change font on "Field Guide' heading to use regular Helvetica or similar (to match logo)

**Comment by kylie-m** [comment]
Adding to this, the favicon is a darker colour than the one used on the rest of the site. It should be ALA's 'Flamingo' colour (#F26649)

The fonts used throughout should be (if available) Lato for headers and Roboto for the rest. If not available, Calibri, or Arial/Helvetica are acceptable

**Comment by adam-collins** [comment]
related to #29

**Comment by kylie-m** [comment]
completed, #39
