### ISSUE TITLE
fieldguide OpenID Connect update

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/fieldguide#19]
grails, oidc and openapi

**Comment by adam-collins** [comment]
- https://github.com/AtlasOfLivingAustralia/fieldguide/pull/20
- https://fieldguide-test.ala.org.au/
- ansible updated

ready for review, testing, gateway setup

**Comment by adam-collins** [comment]
https://fieldguide-test.ala.org.au/openapi/openapi.json

**Comment by adam-collins** [comment]
An email in the auth-test environment is required.

**Comment by kylie-m** [comment]
With adding email I've been able to advance to getting the below response, but it seems to be stuck on 'running' status for a while now (couple of hours)

{"status":"running","statusUrl":"https://fieldguide-test.ala.org.au/generate/status/06102022-fieldguide1665014081978.pdf"}

**Comment by yasima-csiro** [comment]
Released to Prod.
