### ISSUE TITLE
Add author credit to Museums Field Guide table on species pages

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/fieldguide#21]
On some species pages, a Museums Field Guide table appears with additional information, eg: https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/e6aff6af-ff36-4ad5-95f2-2dfdcca8caff

This data comes from this list and is displayed for any species on this list: https://lists.ala.org.au/speciesListItem/list/dr1146

Author credit is the last column in the list, so the information is available, but it's not currently displayed in the table on species pages. This info is contributed by multiple people from multiple museums so it makes sense to directly credit the author.

Reported by @timhicks-ala

**Comment by sat01a** [comment]
@sughics adding this to do the todo list

**Comment by adam-collins** [comment]
addressed in commit https://github.com/AtlasOfLivingAustralia/ala-bie-hub/commit/4eb4ee47aa85da0fd81a8f8c409b3e73e111d9ee

**Comment by adam-collins** [comment]
This was an ala-bie-hub now fixed.
