### ISSUE TITLE
Field guide download showing status: error even when successful

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/fieldguide#24]
The Field Guide download is currently showing status: `error` 

Downloads seem to be running successfully though, with an email sent. i.e. the email arrives and the field guide is generated.

![Screen Shot 2023-08-16 at 4 34 24 pm](https://github.com/AtlasOfLivingAustralia/fieldguide/assets/90439797/18175905-f51f-431e-90c0-209ae1f5129a)

**Comment by kylie-m** [comment]
Example workflow

1. Query Biocache e.g. https://biocache.ala.org.au/occurrences/search?q=lsid:https://biodiversity.org.au/afd/taxa/1e362474-a4f2-43af-8470-446a3f9e7d98#tab_recordsView
2. Download 
3. select 'Species-fieldguide' option 
4. next 
--> this is where the error status shows up

**Comment by timhicks-ala** [comment]
Raised in https://support.ehelp.edu.au/a/tickets/182739

**Comment by yasima-csiro** [comment]
The issue was CORS error. It has been fixed once we start to use api gateway urls.

**Comment by yasima-csiro** [comment]
Tested by Kylie
https://csiroau.sharepoint.com/:x:/r/sites/AtlasofLivingAustraliaTeams/_layouts/15/Doc.aspx?sourcedoc=%7B332D9ECD-A56E-4F22-8CD2-9894A648B52B%7D&file=fieldguide-test-12-oct-2023.xlsx&action=default&mobileredirect=true

**Comment by yasima-csiro** [comment]
Released with 3.1.0
