### ISSUE TITLE
Field Guide generating blank PDF or no result with some queries

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/fieldguide#25]
From helpdesk ticket: https://support.ehelp.edu.au/a/tickets/183279

Downloading a field guide of this search produces nothing (no email, no PDF): https://avh.ala.org.au/occurrences/search?q=taxa%3A%22Scheffler%22&disableAllQualityFilters=true&qc=data_hub_uid%3Adh9#tab_recordsView

Downloading a field guide of a smaller (6 species) selection of the same produces a PDF that is mostly empty: https://avh.ala.org.au/occurrences/search?q=taxa%3A%22Scheffler%22&disableAllQualityFilters=true&qc=data_hub_uid%3Adh9&fq=taxon_name%3A%22Grewia%22

The result is the same whether on AVH or Biocache hub.

In all cases, the download page currently shows an error; this is due to an unrelated issue: https://github.com/AtlasOfLivingAustralia/fieldguide/issues/24

This ticket may be related - a user is attempting to generate a field guide with 124 species: https://support.ehelp.edu.au/a/tickets/183179

Also related:
https://support.ehelp.edu.au/a/tickets/183597

**Comment by yasima-csiro** [comment]
It seems the reason for generating empty pdfs is not receiving proper guids from biocache-hubs. Following is what fieldguide received.

<img width="1210" alt="image" src="https://github.com/AtlasOfLivingAustralia/fieldguide/assets/72474143/3a6bdeb2-ed66-4863-be49-0c8025096e09">

This should be an issue in downloads-plugin.

**Comment by yasima-csiro** [comment]
Closing since this is not a fieldguide issue.
