### ISSUE TITLE
Update species images in Fieldguide to be prioritised image from BIE

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/fieldguide#26]
The recent update to allow image prioritisation in the BIE doesn't yet flow on to ALA Fieldguide. It would be excellent to add this feature.

User story: As an ALA user, I'd like to see a good-quality species image in the Fieldguide, that represents what the species looks like.

Further info: 
- Make sure Fieldguide uses prioritised images from BIE
- These are available in the API: `BIE / search` (https://docs.test.ala.org.au/openapi/index.html?urls.primaryName=species#/Search/Search%20the%20BIE) under  the 'image' field as comma delimited
- There is also a list generated in specieslist (https://lists-test.ala.org.au/speciesListItem/list/dr4778)

**Comment by adam-collins** [comment]
fieldguide uses the bie-index service `/species/guids/bulklookup`. This returns with information about the first preferred image. This request is not cached.

Closing this issue because this is current behaviour.
