### ISSUE TITLE
Field guides not working

### ISSUE THREAD

**Issue by ryonen** [AtlasOfLivingAustralia/fieldguide#6]
Field guides aren't currently working.

In avh-test you firstly get this screen, which comes up instantly and I’m pretty sure shouldn’t say “readynull”:
 
![pilbaraplants_fieldguide_avhtest](https://user-images.githubusercontent.com/17041641/26859188-a0b0c1dc-4b68-11e7-8b2b-036833d5873c.png)

But when you click on the “View…” button, it doesn’t give you a field guide, but brings up this Field Guide Generator screen:
![pilbaraplants_fieldguide_generator_avhtest](https://user-images.githubusercontent.com/17041641/26859196-aacc3e80-4b68-11e7-8761-3ed53b87ba4d.png)

I had a quick play with generating a Field Guide through an ALA Area Search, but just get a 504 Gateway Time Out message.

**Comment by adam-collins** [comment]
avh-test is attempting to use offline fieldguide generation which is not yet deployed.

**Comment by adam-collins** [comment]
currently working
