### ISSUE TITLE
Field guide only contains a proportion of the taxa in the complete download or species checklist

### ISSUE THREAD

**Issue by ryonen** [AtlasOfLivingAustralia/fieldguide#7]
A search on plants in the Pilbara IBRA region produces a download of 48,700 records (http://avh-test.ala.org.au/occurrences/search?q=cl1048%3APilbara&qc=data_hub_uid:dh9&fq=kingdom%3A%22Plantae%22). 

The Species checklist download for the same search has 1,812 unique name identifiers (for species-ranked names only; however, the Species field guide has only 149 names and associated information (a list is attached). 

As an example, there are three species of Tephrosia in the field guide (including one phrase name), but there are close to 40 names in the full data download; and another – none of the five + species of Zygophyllum appear in the checklist at all... There doesn’t seem to be any pattern as to why some taxa appear in the field guide and others don’t.  ?
[Taxon list from field guide.docx](https://github.com/AtlasOfLivingAustralia/fieldguide/files/1056850/Taxon.list.from.field.guide.docx)

**Comment by adam-collins** [comment]
The species included in the fieldguide are the first 149 or so, I think it is alphabetical by species LSID. If making a change I would suggest descending order occurrences.

The limit is for processing time and field guide file size, should someone decide to downloading a field guide for all species. Should the limit change or not, it does need to be listed on a page somewhere.

**Comment by ryonen** [comment]
When you say 'descending order occurrences' are you proposing this to apply to individual taxa across the board regardless of classification, so the taxa would be mixed as shown below?

e.g. [plants only] 
1) jarrah tree (Eucalyptus; Myrtaceae) - 403 records; 
2) she-oak (Allocasuarina; Casuarinaceae) - 376 records; 
3) firewood banksia (Banksia; Proteaceae) - 350 records; 
4) weeping peppermint (Agonis; Myrtaceae) - 278 records; 
5) lovegrass (Eragrostis; Poaceae) - 245 records; 
6) swan river myrtle (Hypocalymma; Myrtaceae) - 234 records; 
7) pixie-mops (Isopogon; Proteaceae) - 210 records; 
8) swamp banksia (Banksia; Proteaceae) - 196 records etc.

Asking because an important point raised by Gen Walker-Smith (zoological CCC) is that taxa presented in the field guide need to be organised by group (i.e. all the members of a genus together; all the genera in a family together) to make the guide useful in the field as an identification tool. Descending order of occurrence (of individual taxa) is a surefire way to mix everything up and negate the entire document, for professionals and the general public.

If it's proposed to use occurrences as a means of filtering the guide to the general public in the assumption that they're the taxa they're most likely to see, it needs to be remembered that the number of occurrence records doesn't necessarily equate to commonality on-ground. People frequently don't record or collect the most common things; almost nobody will collect a specimen of a jarrah tree in a jarrah forest...

Re time & size: I, for one, would be happy to wait half a day or more for a (more-)complete field guide to be queued and downloaded from an ALA URL instead of seeing it truncated. Researchers have as much use for field guides as naturalists and school kids, so it'd be a real shame to produce field guides that are really superficial given that there's all that great data there.

I know that printed and bound field guides are never comprehensive, so wishing for an ALA field guide to be so is probably pushing it a bit, but if it has to be truncated, mimic the real thing (i.e. a good field guide, with good representation of major groups and the major genera and iconic species in them) and you'll probably end up with something that makes the majority of people happy.

**Comment by ryonen** [comment]
During some work yesterday, it was great to see all the species present in the Species checklist download (some 650 spp.) were in the Field guide. Thanks!
See: https://fieldguide.ala.org.au/download/offline/07112017-fieldguide1510027020487.pdf
