### ISSUE TITLE
Verbose logging in prod

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/fieldguide#8]
`catalina.out` is showing hundreds of lines of output for every request that looks like a `system.println` style logging (so not log4j).

Track down the culprit and convert to log4j or remove.

E.g.

> Malvaceae={Common sida=[{imageDataResourceUrl=http://www.bushheritage.org.au/places-we-protect/state_queensland/reserves_carnarvon, scientificName=Sida rhombifolia, smallImageUrl=http://images.ala.org.au/image/proxyImageThumbnailLarge?imageId=b19f9981-242c-4537-9b20-5bfb245a8668, genus=Sida, imageCreator=, imageRights=, guid=http://id.biodiversity.org.au/node/apni/2909922, author=L., phylum=Charophyta, rank=species, classs=Equisetopsida, kingdom=Plantae, order=Malvales, datasetID=dr5214, nameComplete=Sida rhombifolia L., family=Malvaceae, datasetName=Australian Plant Census, thumbnailUrl=http://images.ala.org.au/image/proxyImageThumbnail?imageId=b19f9981-242c-4537-9b20-5bfb245a8668, name=Sida rhombifolia, largeImageUrl=http://images.ala.org.au/image/proxyImage?imageId=b19f9981-242c-4537-9b20-5bfb245a8668, commonNameSingle=Common sida, imageDataResourceName=Bush Heritage - Carnarvon Station Reserve, imageDataResourceUid=dr1030}], Red-flowered Mallow=[{imageDataResourceUrl=http://www.flickr.com/groups/encyclopedia_of_life/, scientificName=Modiola caroliniana, smallImageUrl=http://images.ala.org.au/image/proxyImageThumbnailLarge?imageId=fba7a160-0868-4c02-a4e8-71088bb62316, genus=Modiola, imageCreator=, imageRights=, guid=http://id.biodiversity.org.au/node/apni/2914881, author=(L.) G.Don, phylum=Charophyta, rank=species, linkIdentifier=Modiola caroliniana, classs=Equisetopsida, kingdom=Plantae, order=Malvales, datasetID=dr5214, nameComplete=Modiola caroliniana (L.) G.Don, family=Malvaceae, datasetName=Australian Plant Census, thumbnailUrl=http://images.ala.org.au/image/proxyImageThumbnail?imageId=fba7a160-0868-4c02-a4e8-71088bb62316, name=Modiola caroliniana, largeImageUrl=http://images.ala.org.au/image/proxyImage?imageId=fba7a160-0868-4c02-a4e8-71088bb62316, commonNameSingle=Red-flowered Mallow, imageDataResourceName=Encyclopedia of Life Images - Flickr Group, imageDataResourceUid=dr360}]}

and there are many such entries per download.

**Comment by adam-collins** [comment]
commit https://github.com/AtlasOfLivingAustralia/fieldguide/commit/26b3e75c962b3dac59f39b848852059cb98305be
