### ISSUE TITLE
User suggestions

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/fieldguide#9]
Sent by Helen O:

> We really like your field guide tool and are hoping to use it here in SA to promote interest in park visitation through our “Park of the Month”  web promotions.
>  
> The example in the email below helps us to showcase the species of Gum tree that may be encountered while walking through this particular park (we havent added this to out park website yet).
>  
> There are just a few things we would like to tweak and wondering what you think and what capacity you have to adjust the field guide output.
>  
> 1) Can it include the Common Name?
>  
> 2) The image format is random; ie close up of some , full tree for others. We had 3 thoughts on improving this;
>  
> Can we influence which image will be displayed?
>  
> Can you display maybe 4 smaller images rather than 1 large one.  
>  
> Could you include a url below the image  (“additional images”) that takes the user to all the images for that species (obviously of no use if they wish to print the guide to take in the field).
>  
> 3) Can it have a header – maybe using the text from the ‘selected filter’ text string.

**Comment by adam-collins** [comment]
moved to #29
